#client客户端的ID
uid: 123456
#服务器msqservice地址
msgservice: 127.0.0.1:11881
#BOSS的路径api前缀，用于消息转发
boss: http://139.199.60.49:2180
#文件存储路径,log
log_path: ./
#监控上报地址，调用ymonitor地址，用于心跳反馈问题
monitor: http://139.199.60.49:2180/oservice/Heartbeat/index
#心跳时间 s
heartbeat: 30
